project:
  type: website
  render:
    - "*.qmd"
    - "!FollowAlong/*.qmd"


output-dir: docs/

website:
  title: "Intro to Python Workshops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sessions.qmd
      - link.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-line-numbers: true
    link-external-icon: false
    link-external-newwindow: true



