project:
  type: website
  output-dir: ../docs
  render:
    always-create-output-dir: true
    - "*.qmd"
    - "!FollowAlong/*.qmd"
    - "!ignore*.qmd"
    - "!ignore*.ipynb"
    - session3/*.ipynb
    - "!Downloadable/*.yml"
    - "!session4_newMLDemo/session4_homework_blank.ipynb"

resources:
  - docs/session2
  - docs/session3

website:
  title: "Intro to Python Workshops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Tutorials"
        menu: 
          - text: "All Sessions"
            href: sessions.qmd
          - text: "Session 1: Get Started with Python"
            href: session1/PythonInstallation.qmd
          - text: "Session 2: Intro to Python Data Structures"
            href: session2/DataStructuresDemo.qmd
          - text: "Session 3: Intro to Panda and great_tables"
            href: session3/DataStructuresDemo_2.qmd
          - text: "Session 4: Object-Oriented Programming and Modeling Libraries"
            href: "session4/session4v2_webpage.html"
      - text: "Discussion"
        href: https://github.mskcc.org/Python-Workshop/Python-Workshop.github.io/discussions
      - text: "Links"
        menu:
          - text: "All Links"
            href: link.qmd
          - text: "Install Anaconda"
            href: https://www.anaconda.com/download/success
          - text: "Follow Along Files"
            href: https://github.mskcc.org/Python-Workshop/Python-Workshop.github.io/tree/main/FollowAlong
      - FAQ.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-line-numbers: true
    link-external-icon: false
    link-external-newwindow: true



