project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
    - "!FollowAlong/*.qmd"
    - "!ignore*.qmd"
    - "!ignore*.ipynb"
    - session3/*.ipynb
    - "!Downloadable/*.yml"

website:
  title: "Intro to Python Workshops"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Sessions"
        menu: 
          - text: "All Sessions"
            href: sessions.qmd
          - text: "Session 1: Get Started with Python"
            href: session1/PythonInstallation.qmd
          - text: "Session 2a: Intro to Python Data Structures"
            href: session2a/DataStructuresDemo.qmd
          - text: "Session 2b: Intro to Pandas"
            href: session2b/DataStructuresDemo_2.qmd
          - text: "Session 3: Logistic Regression Demo"
            href: session3/PythonMLDemo.qmd
          - text: "Extras: Regex Tutorial"
            href: extra_tutorials/regex_tutorial.qmd
      - text: "Discussion"
        href: https://github.mskcc.org/Python-Workshop/Python-Workshop.github.io/discussions
      - text: "Links"
        menu:
          - text: "All Links"
            href: link.qmd
          - text: "Install Anaconda"
            href: https://www.anaconda.com/download/success
          - text: "Follow Along Files"
            href: https://github.mskcc.org/Python-Workshop/Python-Workshop.github.io/tree/main/FollowAlong
      - FAQ.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-line-numbers: true
    link-external-icon: false
    link-external-newwindow: true



