project:
  type: website
  output-dir: ../docs
  render:
    - "*.qmd"
    - "!FollowAlong/*.qmd"
    - "!ignore*.qmd"
    - "!ignore*.ipynb"
    - session3/*.ipynb
    - "!Downloadable/*.yml"
    - "!session4_newMLDemo/session4_homework_blank.ipynb"

resources:
  - docs/session2
  - docs/session3

website:
  title: "Intro to Python Workshops"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**WIP** - This website is currently undergoing some updates. Content is subject to change."
    position: below-navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Tutorials"
        menu: 
          - text: "All Sessions"
            href: sessions.qmd
          - text: "Session 1: Get Started with Python"
            href: session1/PythonInstallation.qmd
          - text: "Session 2: Intro to Python Data Structures"
            href: session2/DataStructuresDemo.qmd
          - text: "Session 3: Intro to Pandas and great_tables"
            href: session3/Session_3.qmd
          - text: "Session 4: Object-Oriented Programming and Modeling Libraries"
            href: "session4/session4v3_webpage.html"
      - text: "Extras"
        menu: 
          - text: "Using Venv for Python Virtual Environents"
            href: "extra_tutorials/venvlikeconda.qmd"
          - text: "Creating a Python Package"
            href: "extra_tutorials/creatingsimplepackage.qmd"
      - text: "Discussion"
        href: https://github.com/PythonForRUsers/Python-Workshop.github.io/discussions
      - text: "Links"
        menu:
          - text: "All Links"
            href: link.qmd
          - text: "Install Python"
            href: "https://www.python.org/downloads/"
          - text: "Install Positron"
            href: https://positron.posit.co/download.html
          - text: "Follow Along Files"
            href: https://github.com/PythonForRUsers/Python-Workshop.github.io/tree/main/FollowAlong
      - FAQ.qmd
      

format:
  html:
    theme: 
      - brand
      - cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-line-numbers: true
    link-external-icon: false
    link-external-newwindow: true



