name: python-intro-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - ipykernel
  - pyyaml
  - numpy
  - pandas
  - great_tables
  - plotnine
  - seaborn
  - scikit-learn
  - statsmodels
  - nbformat #optional
  - statsmodels
