name: python-intro-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pandas
  - numpy
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - pyyaml
  - nbformat #optional
